### ISSUE TITLE
Exception when running sample

### ISSUE THREAD

**Issue by zluiten** [dataanon/dataanon-kotlin-sample#1]
First of all, I'm not a daily user of Java or Kotlin, but since this looks like a nice tool (especially that one can write his own AnonymizationStrategy) I absolutely want to give this a try. I'm getting the follow exception when running the project with `mvn exec:java`. Any idea what I'm doing wrong?

```
➜  dataanon-kotlin-sample git:(master) mvn exec:java
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building dataanon-kotlin-sample 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ dataanon-kotlin-sample ---
[DEBUG] (com.github.dataanon.AnonymizerKt.main()) Using Console logging
SELECT MOVIE_ID,RELEASE_DATE,TITLE,GENRE FROM MOVIES  WHERE GENRE = 'Drama'
SELECT MOVIE_ID,USER_ID,CREATED_AT,RATING FROM RATINGS
INSERT INTO MOVIES(MOVIE_ID, RELEASE_DATE, TITLE, GENRE) VALUES(?,?,?,?)
INSERT INTO RATINGS(MOVIE_ID, USER_ID, CREATED_AT, RATING) VALUES(?,?,?,?)
MOVIES   0% [>                                                                                        ]      0/100000 (0:00:00 / ?) RATMOVIES   0% [>                                                                                        ]      0/100000 (0:00:01 / ?) RATINGS   0% [>                                                                                                 ] 0/6 (0:00:01 / ?)

[ERROR] (parallel-1) Scheduler worker in group com.github.dataanon.AnonymizerKt failed with an uncaught exception - kotlin.UninitializedPropertyAccessException: lateinit property stmt has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property stmt has not been initialized
	at com.github.dataanon.jdbc.TableWriter.hookFinally(TableWriter.kt:62)
	at reactor.core.publisher.BaseSubscriber.safeHookFinally(BaseSubscriber.java:241)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:185)
	at reactor.core.publisher.BaseSubscriber.onSubscribe(BaseSubscriber.java:149)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:128)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:61)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at com.github.dataanon.dsl.Strategy.executeOnTable(Strategy.kt:34)
	at com.github.dataanon.dsl.Strategy.access$executeOnTable(Strategy.kt:14)
	at com.github.dataanon.dsl.Strategy$execute$1.accept(Strategy.kt:23)
	at com.github.dataanon.dsl.Strategy$execute$1.accept(Strategy.kt:14)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:396)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:480)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:69)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] (parallel-2) Scheduler worker in group com.github.dataanon.AnonymizerKt failed with an uncaught exception - kotlin.UninitializedPropertyAccessException: lateinit property stmt has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property stmt has not been initialized
	at com.github.dataanon.jdbc.TableWriter.hookFinally(TableWriter.kt:62)
	at reactor.core.publisher.BaseSubscriber.safeHookFinally(BaseSubscriber.java:241)
	at reactor.core.publisher.BaseSubscriber.onError(BaseSubscriber.java:185)
	at reactor.core.publisher.BaseSubscriber.onSubscribe(BaseSubscriber.java:149)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:128)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:61)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at com.github.dataanon.dsl.Strategy.executeOnTable(Strategy.kt:34)
	at com.github.dataanon.dsl.Strategy.access$executeOnTable(Strategy.kt:14)
	at com.github.dataanon.dsl.Strategy$execute$1.accept(Strategy.kt:23)
	at com.github.dataanon.dsl.Strategy$execute$1.accept(Strategy.kt:14)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:396)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:480)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:69)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] thread Thread[parallel-1,5,com.github.dataanon.AnonymizerKt] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[parallel-1,5,com.github.dataanon.AnonymizerKt] will linger despite being asked to die via interruption
[WARNING] thread Thread[parallel-2,5,com.github.dataanon.AnonymizerKt] will linger despite being asked to die via interruption
[WARNING] NOTE: 2 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.github.dataanon.AnonymizerKt,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:778)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.088 s
[INFO] Finished at: 2018-02-28T22:19:18+01:00
[INFO] Final Memory: 10M/205M
[INFO] ------------------------------------------------------------------------
```

**Comment by sunitparekh** [comment]
first of all thanks for trying out the tool and thanks for feedback.

looks like table creation steps using scripts provided is missed. you will find scripts in resources folder
https://github.com/dataanon/dataanon-kotlin-sample/tree/master/src/main/resources

FYI, we are working on handling errors and few other features. we are going to publish snapshot version soon for your play with, which will be having better error handling.

**Comment by zluiten** [comment]
@sunitparekh Thanks for helping out, it works! Looks very nice and a great project to get familiar with Kotlin 👍

**Comment by sunitparekh** [comment]
@netiul please do share feedback of tool. Also let us know if you need any specific feature by creating issue on GitHub.
